In [44]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [45]:
df = pd.read_csv('netflix_titles.csv')

In [46]:
df.head()

  show_id  ...                                        description
0      s1  ...  As her father nears the end of his life, filmm...
1      s2  ...  After crossing paths at a party, a Cape Town t...
2      s3  ...  To protect his family from a powerful drug lor...
3      s4  ...  Feuds, flirtations and toilet talk go down amo...
4      s5  ...  In a city of coaching centers known to train I...

[5 rows x 12 columns]

In [47]:
df.tail()

     show_id  ...                                        description
8802   s8803  ...  A political cartoonist, a crime reporter and a...
8803   s8804  ...  While living alone in a spooky town, a young g...
8804   s8805  ...  Looking to survive in a world taken over by zo...
8805   s8806  ...  Dragged from civilian life, a former superhero...
8806   s8807  ...  A scrappy but poor boy worms his way into a ty...

[5 rows x 12 columns]

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [49]:
df.describe().astype(int)

       release_year
count          8807
mean           2014
std               8
min            1925
25%            2013
50%            2017
75%            2019
max            2021

In [50]:
missing = df.isna().sum()
missing_pct = (missing / len(df)) * 100

In [51]:
missing_df = pd.DataFrame({'Missing_Values': missing,
                           "Percentage %": missing_pct.round(2)})
print(missing_df[missing_df['Missing_Values'] > 0])

            Missing_Values  Percentage %
director              2634         29.91
cast                   825          9.37
country                831          9.44
date_added              10          0.11
rating                   4          0.05
duration                 3          0.03

In [52]:
df['director'].fillna('Unknown', inplace= True)
df['cast'].fillna('Unknown', inplace= True)
df['country'].fillna('Unknown', inplace= True)
df['rating'].fillna('Unknown', inplace= True)

# Drop rows where 'date_added' or 'duration' is missing (very few)
df.dropna(subset= ['date_added', 'duration'], inplace= True)

/tmp/ipykernel_484/3502603819.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['director'].fillna('Unknown', inplace= True)
/tmp/ipykernel_484/3502603819.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cast'].fillna('Unknown', inplace= True)
/tmp/ipykernel_484/3502603819.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['country'].fillna('Unknown', inplace= True)
/tmp/ipykernel_484/3502603819.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['rating'].fillna('Unknown', inplace= True)

In [53]:
df['date_added'] = pd.to_datetime(df['date_added'].str.strip())

In [54]:
df['year_added'] = df['date_added'].dt.year
df['month_year'] = df['date_added'].dt.month_name()

In [58]:
print('Data Cleaned')
print(f'Remaning rows: , {df.shape[0]}')

Data Cleaned
Remaning rows: , 8794

In [56]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
year_added      0
month_year      0
dtype: int64

In [64]:
print('Content Type Count:')
print(df['type'].value_counts())
print()

Content Type Count:
type
Movie      6128
TV Show    2666
Name: count, dtype: int64

In [66]:
print('Percentage Split:')
print(df['type'].value_counts(normalize= True).mul(100).round(1).astype(str) + '%')

Percentage Split:
type
Movie      69.7%
TV Show    30.3%
Name: proportion, dtype: object